### ISSUE TITLE
If you follow the directions, the app won't build due to dependency issue with SingletonEhCacheRegionFactory

### ISSUE THREAD

**Issue by chriserickson** [grails-guides/grails-multi-project-build#4]
To fix, you need to remove this from the generated app.yaml
```
hibernate:
     cache:
         region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
```

**Comment by sdelamo** [comment]
The project that not contain that configuration: 

` grails-guides/grails-multi-project-build$ grep -inr org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory *`

returns no result

**Comment by chriserickson** [comment]
Correct.

What I did was follow the tutorial, line-by-line, creating my own project as I went along. 
My Grails (3.2.8) project did, and caused things not to work.

**Comment by sdelamo** [comment]
Second level cache is now turned off by default:

https://github.com/grails-profiles-versions/web-versions/compare/3.2.8...3.3.1
